server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/SkincareBookingDB"
    username: root
    password: 0812181639ghjm


    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: true



jwt:
  signerKey: "83cOZvIL67/0XUWfDO/vptHrYkL6FTxO1EGp/GU6Rjk3k3OQjBDbj58Xk8GoDQyU"