server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/SkincareBookingDB"
    username: root
    password: 123456quyen

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: systemskincarebooking@gmail.com
    password: "cgnm vjad nldx neup"
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

jwt:
  signerKey: "83cOZvIL67/0XUWfDO/vptHrYkL6FTxO1EGp/GU6Rjk3k3OQjBDbj58Xk8GoDQyU"