server:
  port: 8080
  servlet:
    context-path:

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/SkincareBookingDB"
    username: root
    password: 0812181639ghjm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

